[package]
name = "texas-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9"
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
itertools = "0.14"

[dev-dependencies]
rstest = "0.25"
